services:
  service1_1:
    build: ./service1
    container_name: service1_1
    depends_on:
      - service2
    networks:
      - loadbalancing

  service1_2:
    build: ./service1
    container_name: service1_2
    depends_on:
      - service2
    networks:
      - loadbalancing

  service1_3:
    build: ./service1
    container_name: service1_3
    depends_on:
      - service2
    networks:
      - loadbalancing

  service2:
    build: ./service2
    container_name: service2
    networks:
      - loadbalancing

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - service1_1
      - service1_2
      - service1_3
      - service2
    ports:
      - "8198:80"
    networks:
      - loadbalancing

networks:
  loadbalancing:
