services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8199:8199"
    depends_on:
      - service2

  service2:
    build: ./service2
    container_name: service2
